## Perceptron
### **m** input features and **n** output results

### Import modules

In [1]:
import numpy as np
import pandas as pd
from perceptron import Perceptron

### Define training set for wines evaluation
* Feature 1: sweetness of the wine
* Feature 2: acidity of the wine
* Feature 3: power of wine

Result: 1 good 0 not good

In [2]:
training_set = [
    ([0.0, 1.0, 1.0], [0.0]),
    ([1.0, 0.0, 0.0], [1.0]),
    ([0.5, 0.5, 0.5], [1.0])
]

### Perceptron learning


In [3]:
perceptron = Perceptron(training_set, 1000)
print("Initial weights: \n", perceptron.weights)
perceptron.learning()
print("Learnt weights: \n", perceptron.weights)


Initial weights: 
 [[-0.86462607 -0.60769247 -0.49756737 -0.06927532]]
Learnt weights: 
 [[-0.86462607 -0.30769247 -0.79756737 -0.36927532]]


### Define input vector and run perceptron

In [4]:
net_input = [1.0, 0.0, 0.0]
output = perceptron.run([net_input])
print("Output for ", net_input, " is ", output)

Output for  [1.0, 0.0, 0.0]  is  [1]


### Save weight matrix on the disk

In [5]:
np.save('weight_matrix', perceptron.weights)

### Create new perceptron net a set its weights from disk

In [6]:
perceptron = Perceptron(training_set, 1000)
print("Initial weights: \n", perceptron.weights)
perceptron.weights = np.load('weight_matrix.npy')
print("Learnt weights: \n", perceptron.weights)

Initial weights: 
 [[-1.91735421  0.15858829  0.31831874 -0.21528747]]
Learnt weights: 
 [[-0.86462607 -0.30769247 -0.79756737 -0.36927532]]


### Using Excel Table to define training set

### Wines Excel file

In [7]:
data = pd.read_excel('wines.xlsx')
data.head()
training_set = []
for index, row in data.iterrows():
    features = [row['Sweetness'], row['Acidity'], row['Power']]
    result = [row['Good']]
    training_set.append((features, result))
#print("Transformations: ", training_set)
training_set



[([0.0, 1.0, 1.0], [0.0]), ([1.0, 0.0, 0.0], [1.0]), ([0.5, 0.5, 0.5], [1.0])]

### Diagnosis learning verification

Training set consist of several patients, where symptoms are associates with diagnosis. The goal is to learn from this examples.

In [8]:
data = pd.read_excel('diagnosis.xlsx')
data.head()
training_set = []
for index, row in data.iterrows():
    features = [row['Fever'], row['Cough'], row['Headache'], row['Tiredness'], row['Night Sweat']]
    result = [row['Pneumonia'], row['Flu'], row['Cold']]
    training_set.append((features, result))

perceptron = Perceptron(training_set, 1000)
perceptron.learning()

for row in training_set:
    net_input = row[0]
    net_output = perceptron.run(net_input)
    print("Input: ", net_input, " Output: ", net_output)

header = list(data.columns)
 

Input:  [0.0, 0.5, 0.5, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 1.0, 1.0, 1.0, 0.0]  Output:  [0, 1, 0]
Input:  [0.5, 1.0, 0.0, 1.0, 1.0]  Output:  [1, 0, 0]
Input:  [0.0, 0.5, 0.0, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 0.5, 1.0, 0.5, 0.0]  Output:  [0, 1, 0]
Input:  [1.0, 1.0, 0.0, 0.5, 0.5]  Output:  [1, 0, 0]


### Usage of diagnosis app
Input data are read from excel file and diagosis is inferred from the learnt net o perceptrons.

In [9]:
input_data = pd.read_excel('diagnosis_input.xlsx')
input_data.head()
input_set = []
for index, row in input_data.iterrows():
    features = [row['Fever'], row['Cough'], row['Headache'], row['Tiredness'], row['Night Sweat']]
    input_set.append(features)

output_set = []
for net_input in input_set:
    net_output = perceptron.run(net_input)
    output_set.append(net_output)
    print("Input: ", net_input, " Output: ", net_output)
# Create a DataFrame for the output data

header = list(data.columns)
output_data = pd.DataFrame(columns=header)

for i in range(len(input_set)):
    row = input_set[i] + output_set[i]
    output_data.loc[i] = row

output_data.to_excel('diagnosis_output.xlsx', index=False)
output_data



Input:  [0.0, 0.5, 0.0, 0.0, 0.0]  Output:  [0, 0, 1]
Input:  [1.0, 1.0, 1.0, 1.0, 0.0]  Output:  [0, 1, 0]
Input:  [0.5, 1.0, 0.0, 1.0, 1.0]  Output:  [1, 0, 0]
Input:  [1.0, 0.5, 0.5, 0.5, 0.0]  Output:  [0, 0, 0]
Input:  [0.0, 0.5, 0.0, 0.2, 0.0]  Output:  [0, 0, 1]


Fever  Cough  Headache  Tiredness  Night Sweat  Pneumonia  Flu  Cold
0    0.0    0.5       0.0        0.0          0.0        0.0  0.0   1.0
1    1.0    1.0       1.0        1.0          0.0        0.0  1.0   0.0
2    0.5    1.0       0.0        1.0          1.0        1.0  0.0   0.0
3    1.0    0.5       0.5        0.5          0.0        0.0  0.0   0.0
4    0.0    0.5       0.0        0.2          0.0        0.0  0.0   1.0

### Mean squared error for the training set

In [10]:
mse = perceptron.calculate_mse()
mse

0.0

### Max error of a single neuron withing the complete training set

In [11]:
max = perceptron.calculate_max()
max

0